// src/components/DropArea.tsx
'use client';

import Image from 'next/image';
import { Button, Separator } from '@heroui/react';
import { FolderOpen } from 'lucide-react';
import { useTranslation } from 'react-i18next';
import { useCompressorStore } from '@/providers/compressor-store-provider';

export default function DropArea() {
  const { triggerFileSelect } = useCompressorStore((state) => state);
  const { t } = useTranslation('compressor');

  return (
    <div className="bg-background-secondary h-full w-full rounded-xl border-2 border-dashed">
      <div className="flex h-full w-full flex-col items-center justify-center gap-4">
        <Image alt="center logo" className="opacity-30" height={144} src="/images/logo.png" width={144}></Image>
        <h2 className="text-2xl">{t('drop_here')}</h2>
        <div className="flex w-full max-w-full items-center justify-center gap-2">
          <Separator className="w-1/3"></Separator>
          <span className="text-sm uppercase">{t('or')}</span>
          <Separator className="w-1/3"></Separator>
        </div>
        <Button size="lg" onPress={triggerFileSelect}>
          <FolderOpen />
          {t('browse_dots')}
        </Button>
      </div>
    </div>
  );
}

// components/DropArea.vue
<script setup lang="ts">
import {FolderOpen} from 'lucide-vue-next';

import {useCompressorStore} from '@/stores/compressor'

const compressorStore = useCompressorStore()
</script>

<template>
  <div
      class="min-h-[400px] h-2/3 rounded-md border-dashed flex flex-col flex-1 items-center justify-center gap-4 bg-gray-100 dark:bg-gray-800 border border-gray-300 dark:border-gray-700"
      @drop.prevent="compressorStore.onFilesAdded($event?.dataTransfer?.files)"
      @dragover.prevent>
    <img class="size-36 opacity-30" src="~/assets/images/logo.png" alt="logo">
    <h2 class="font-medium text-2xl">{{ $t('compressor.drop_here') }}</h2>
    <div
        class="w-full sm:w-5/6 py-3 flex items-center text-sm text-gray-800 before:flex-1 before:border-t before:border-gray-300 before:me-6 after:flex-1 after:border-t after:border-gray-300 after:ms-6 dark:text-gray-100 dark:before:border-gray-700 dark:after:border-gray-700">
      {{ $t('compressor.or').toUpperCase() }}
    </div>

    <button
type="button"
            class="transition py-3 px-4 inline-flex items-center gap-x-2 text-sm font-semibold rounded-lg border border-transparent bg-purple-500 text-gray-100 hover:bg-purple-600 disabled:opacity-50 disabled:pointer-events-none"
            @click="compressorStore.addFiles()">
      <FolderOpen class="size-5"/>
      {{ $t('compressor.browse_dots') }}
    </button>
  </div>
</template>

<style scoped>

</style>
