// src/components/layout/Header.tsx
import Image from 'next/image';
import Link from 'next/link';
import { Button } from '@/components/ui/button';
import { getLang } from '@/lib/i18n/lang-context';
import { getServerTranslation } from '@/lib/i18n/server';
import LanguageSwitcher from '@/components/LanguageSwitcher';
import { ThemeSwitcher } from '@/components/ThemeSwitcher';

export default async function Header() {
  const lang = await getLang();
  const { t } = await getServerTranslation(lang, 'common');
  return (
    <header className="bg-background flex h-16 w-full items-center justify-between border-b p-2 px-4 text-sm">
      <Link href="/">
        <div className="flex items-center gap-2">
          <Image alt="logo" height={40} src="/images/logo.png" width={40}></Image>
        </div>
      </Link>
      <div className="flex items-center gap-2">
        {/* <Link href="/about" target="_blank">
          {t('about')}
        </Link> */}
        <Link href="/donate">{t('donate')}</Link>
        <Link aria-label="GitHub" href="https://github.com/Lymphatus/caesium-app-web" target="_blank">
          <Button aria-label="GitHub" className="hover:text-primary hover:bg-primary/10" size="icon" variant="ghost">
            <svg aria-hidden="true" className="size-4 shrink-0" fill="currentColor" height="16" viewBox="0 0 16 16" width="16" xmlns="http://www.w3.org/2000/svg">
              <path d="M8 0C3.58 0 0 3.58 0 8c0 3.54 2.29 6.53 5.47 7.59.4.07.55-.17.55-.38 0-.19-.01-.82-.01-1.49-2.01.37-2.53-.49-2.69-.94-.09-.23-.48-.94-.82-1.13-.28-.15-.68-.52-.01-.53.63-.01 1.08.58 1.23.82.72 1.21 1.87.87 2.33.66.07-.52.28-.87.51-1.07-1.78-.2-3.64-.89-3.64-3.95 0-.87.31-1.59.82-2.15-.08-.2-.36-1.02.08-2.12 0 0 .67-.21 2.2.82.64-.18 1.32-.27 2-.27.68 0 1.36.09 2 .27 1.53-1.04 2.2-.82 2.2-.82.44 1.1.16 1.92.08 2.12.51.56.82 1.27.82 2.15 0 3.07-1.87 3.75-3.65 3.95.29.25.54.73.54 1.48 0 1.07-.01 1.93-.01 2.2 0 .21.15.46.55.38A8.012 8.012 0 0 0 16 8c0-4.42-3.58-8-8-8z" />
            </svg>
          </Button>
        </Link>
        <LanguageSwitcher></LanguageSwitcher>
        <ThemeSwitcher></ThemeSwitcher>
      </div>
    </header>
  );
}

// components/Header.vue
<script setup lang="ts">
import {Languages} from "lucide-vue-next";

const {locales, setLocale} = useI18n()
</script>

<template>
  <header class="flex flex-wrap sm:justify-start sm:flex-nowrap w-full bg-neutral-100 text-sm py-2 dark:bg-neutral-800 border-b border-neutral-200 dark:border-neutral-700">
    <nav class="w-full mx-auto px-4 sm:flex sm:items-center sm:justify-between" aria-label="global">
      <div class="flex items-center justify-between">
        <NuxtLink class="flex items-center gap-2" :to="{name: 'index'}">
          <img class="size-10" src="~/assets/images/logo.png" alt="logo">
          <h2 class="hidden sm:block text-neutral-600 dark:text-neutral-400 text-lg"><span class="font-medium">Caesium</span> Image Compressor</h2>
        </NuxtLink>
        <div class="sm:hidden">
          <button type="button"
                  class="hs-collapse-toggle p-2 inline-flex justify-center items-center gap-x-2 rounded-lg border border-neutral-200 bg-white text-neutral-800 shadow-sm hover:bg-neutral-50 disabled:opacity-50 disabled:pointer-events-none dark:bg-transparent dark:border-neutral-700 dark:text-neutral-100 dark:hover:bg-white/10"
                  data-hs-collapse="#navbar-menu" aria-controls="navbar-menu" aria-label="Toggle navigation">
            <svg class="hs-collapse-open:hidden flex-shrink-0 size-4" xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round"
                 stroke-linejoin="round">
              <line x1="3" x2="21" y1="6" y2="6"/>
              <line x1="3" x2="21" y1="12" y2="12"/>
              <line x1="3" x2="21" y1="18" y2="18"/>
            </svg>
            <svg class="hs-collapse-open:block hidden flex-shrink-0 size-4" xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round"
                 stroke-linejoin="round">
              <path d="M18 6 6 18"/>
              <path d="m6 6 12 12"/>
            </svg>
          </button>
        </div>
      </div>
      <div id="navbar-menu" class="hs-collapse hidden overflow-hidden transition-all duration-300 sm:block">
        <div class="flex flex-col gap-4 mt-5 sm:flex-row sm:items-center sm:justify-end sm:mt-0 sm:ps-5">
          <NuxtLink class="font-medium text-neutral-600 hover:text-purple-400 dark:text-neutral-400 dark:hover:text-purple-500 cursor-pointer" :to="{name: 'about'}">{{ $t('compressor.donate') }}</NuxtLink>

          <div class="hs-dropdown [--strategy:static] sm:[--strategy:fixed] [--adaptive:none] ">
            <button id="hs-mega-menu-basic-dr" type="button" class="flex items-center w-full text-neutral-600 hover:text-purple-400 font-medium dark:text-neutral-400 dark:hover:text-purple-500 ">
              <Languages class="size-4"/>
              <svg class="ms-1 flex-shrink-0 size-4" xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">
                <path d="m6 9 6 6 6-6"/>
              </svg>
            </button>

            <div
                class="hs-dropdown-menu transition-[opacity,margin] duration-[0.1ms] sm:duration-[150ms] hs-dropdown-open:opacity-100 opacity-0 z-10 bg-white sm:shadow-md rounded-lg p-2 dark:bg-neutral-800 sm:dark:border dark:border-neutral-700 dark:divide-neutral-700 before:absolute top-full sm:border before:-top-5 before:start-0 before:w-full before:h-5 hidden">

              <a href="#" v-for="locale in locales" :key="locale.code" @click.prevent.stop="setLocale(locale.code)"
                 class="flex items-center gap-x-3.5 py-2 px-3 rounded-lg text-sm text-neutral-800 hover:bg-neutral-100 focus:ring-2 focus:ring-purple-500 dark:text-neutral-400 dark:hover:bg-neutral-700 dark:hover:text-purple-300">
                <img class="size-4" :src="locale.flag" alt="logo"> {{ locale.code }}
              </a>
            </div>
          </div>

          <button type="button" class="hs-dark-mode-active:hidden block hs-dark-mode group items-center text-neutral-600 hover:text-purple-600 font-medium dark:text-neutral-400 dark:hover:text-purple-500" data-hs-theme-click-value="dark">
            <svg class="flex-shrink-0 size-4" xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">
              <path d="M12 3a6 6 0 0 0 9 9 9 9 0 1 1-9-9Z"></path>
            </svg>
          </button>
          <button type="button" class="hs-dark-mode-active:block hidden hs-dark-mode group items-center text-neutral-600 hover:text-purple-600 font-medium dark:text-neutral-400 dark:hover:text-purple-500" data-hs-theme-click-value="light">
            <svg class="flex-shrink-0 size-4" xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">
              <circle cx="12" cy="12" r="4"></circle>
              <path d="M12 2v2"></path>
              <path d="M12 20v2"></path>
              <path d="m4.93 4.93 1.41 1.41"></path>
              <path d="m17.66 17.66 1.41 1.41"></path>
              <path d="M2 12h2"></path>
              <path d="M20 12h2"></path>
              <path d="m6.34 17.66-1.41 1.41"></path>
              <path d="m19.07 4.93-1.41 1.41"></path>
            </svg>
          </button>
        </div>
      </div>
    </nav>
  </header>
</template>

<style scoped>

</style>
